stages:
    - build
    - build-artifact
    - repository

default:
    image: docker:latest
    before_script: |
        DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME/main/latest}
        if [ ! -z `command -v docker` ]; then
            echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
        fi
    after_script: |
        if [ ! -z `command -v docker` ]; then
            docker logout $CI_REGISTRY
        fi

build:
    stage: build
    script:
        - docker build . --pull --build-arg COMMIT_SHA=$CI_COMMIT_SHA --build-arg FLUX_AUTOLOAD_API_IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-autoload-api --build-arg FLUX_ILIAS_BASE_API_IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-ilias-base-api --build-arg FLUX_NAMESPACE_CHANGER_IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-namespace-changer --build-arg FLUX_REST_API_IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-rest-api -t $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
        - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    only:
        - branches
        - tags

create-gitlab-artifact-from-build:
    stage: build-artifact
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-docker-gitlab-build-artifact:latest
    script:
        - create-gitlab-artifact-from-docker-build $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG /$CI_PROJECT_NAME.tar.gz build.tar.gz
    artifacts:
        paths:
            - build.tar.gz
        expire_in: 5 minutes
    only:
        - /^v[0-9-]+$/

flux-publish-utils:
    stage: repository
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-publish-utils:latest
    script:
        - if [ -n "$CI_COMMIT_TAG" ]; then upload-release-asset build.tar.gz $CI_PROJECT_NAME-$DOCKER_IMAGE_TAG-build.tar.gz; else publish-utils; fi
    only:
        - main
        - /^v[0-9-]+$/
